import { CalendarOutlined, FileDoneOutlined, MailOutlined } from "@ant-design/icons";
import { GetProp, MenuProps } from "antd";

export interface DataType {
  key: string;
  name: string;
  aseguradora?: string;
  tipocliente?: 'Natural' | 'Jurídico';
  ramo?: string;
  coberturaGeneral?: string;
  coberturaAdicional?: string;
  observaciones?: string;
  deducibles?: number;
  formaPago?: 'Financiamento Directo' | "Debito a la Cuenta" | "Tarjeta de Crédito"
}


export const data: DataType[] = [
  {
    key: '1',
    name: 'Sofía Martínez',
    aseguradora: 'PICHINCHA',
    tipocliente: 'Natural',
    ramo: 'Robo',
    coberturaGeneral: "Prueba",
    coberturaAdicional: "Prueba",
    observaciones: "Prueba",
    deducibles: 10,
    formaPago: "Tarjeta de Crédito",
  },
  {
    key: '2',
    name: 'Liam Carter',
    aseguradora: 'EQUINOCCIAL',
    tipocliente: 'Natural',
    ramo: 'Equipo Electrónico',
    coberturaGeneral: "Prueba",
    coberturaAdicional: "Prueba",
    observaciones: "Prueba",
    deducibles: 10,
    formaPago: "Financiamento Directo",
  },
  {
    key: '3',
    name: 'Alejandro Ruiz',
    aseguradora: 'ECUATORIANO SUIZA',
    tipocliente: 'Natural',
    ramo: 'Robo',
    coberturaGeneral: "Prueba",
    coberturaAdicional: "Prueba",
    observaciones: "Prueba",
    deducibles: 10,
    formaPago: "Debito a la Cuenta",
  },
  {
    key: '4',
    name: 'Apptelink S.A.',
    aseguradora: 'LATINA SEGUROS C.A',
    tipocliente: 'Jurídico',
    ramo: 'Transporte',
    coberturaGeneral: "Prueba",
    coberturaAdicional: "Prueba",
    observaciones: "Prueba",
    deducibles: 10,
    formaPago: "Tarjeta de Crédito",
  },
  {
    key: '5',
    name: 'Citikold Group',
    aseguradora: 'COLON',
    tipocliente: 'Jurídico',
    ramo: 'Garantias Aduaneras',
    coberturaGeneral: "Prueba",
    coberturaAdicional: "Prueba",
    observaciones: "Prueba",
    deducibles: 10,
    formaPago: "Debito a la Cuenta",
  },
  {
    key: '6',
    name: 'Amazon',
    aseguradora: 'PICHINCHA',
    tipocliente: 'Jurídico',
    ramo: 'Rotura de Maquinaria',
    coberturaGeneral: "Prueba",
    coberturaAdicional: "Prueba",
    observaciones: "Prueba",
    deducibles: 10,
    formaPago: "Debito a la Cuenta",
  },
  {
    key: '7',
    name: 'Carlos Gómez',
    aseguradora: 'LA UNIÓN',
    tipocliente: 'Natural',
    ramo: 'Robo',
    coberturaGeneral: "Prueba",
    coberturaAdicional: "Prueba",
    observaciones: "Prueba",
    deducibles: 10,
    formaPago: "Tarjeta de Crédito",
  },
  {
    key: '8',
    name: 'Isabella Clark',
    aseguradora: 'COLON',
    tipocliente: 'Natural',
    ramo: 'Vehiculos',
    coberturaGeneral: "Prueba",
    coberturaAdicional: "Prueba",
    observaciones: "Prueba",
    deducibles: 10,
    formaPago: "Financiamento Directo",
  },
  {
    key: '9',
    name: 'Diego Morales',
    aseguradora: 'GENERALI',
    tipocliente: 'Natural',
    ramo: 'Vida Colectiva',
    coberturaGeneral: "Prueba",
    coberturaAdicional: "Prueba",
    observaciones: "Prueba",
    deducibles: 10,
    formaPago: "Debito a la Cuenta",
  },
  {
    key: '10',
    name: 'Amelia Foster',
    aseguradora: 'COFACE S.A.',
    tipocliente: 'Natural',
    ramo: 'Fidelidad',
    coberturaGeneral: "Prueba",
    coberturaAdicional: "Prueba",
    observaciones: "Prueba",
    deducibles: 10,
    formaPago: "Financiamento Directo",
  },
  {
    key: '11',
    name: 'Gabriel Silva',
    aseguradora: 'LA UNIÓN',
    tipocliente: 'Natural',
    ramo: 'Cumplimiento de Contrato',
    coberturaGeneral: "Prueba",
    coberturaAdicional: "Prueba",
    observaciones: "Prueba",
    deducibles: 10,
    formaPago: "Debito a la Cuenta",
  },
  {
    key: '12',
    name: 'Chloe Hayes',
    aseguradora: 'SEGUROS CONFIANZA S.A.',
    tipocliente: 'Natural',
    ramo: 'Cumplimiento de Contrato',
    coberturaGeneral: "Prueba",
    coberturaAdicional: "Prueba",
    observaciones: "Prueba",
    deducibles: 10,
    formaPago: "Financiamento Directo",
  },
];

export const dataUser: DataType[] = [
  {
    key: '1',
    name: 'Sofía Martínez',
    aseguradora: 'PICHINCHA',
    tipocliente: 'Natural',
    ramo: 'Robo',
    coberturaGeneral: "Prueba",
    coberturaAdicional: "Prueba",
    observaciones: "Prueba",
    deducibles: 10,
    formaPago: "Tarjeta de Crédito",
  },
  {
    key: '2',
    name: 'Sofía Martínez',
    aseguradora: 'EQUINOCCIAL',
    tipocliente: 'Natural',
    ramo: 'Equipo Electrónico',
    coberturaGeneral: "Prueba",
    coberturaAdicional: "Prueba",
    observaciones: "Prueba",
    deducibles: 10,
    formaPago: "Financiamento Directo",
  },
  {
    key: '3',
    name: 'Sofía Martínez',
    aseguradora: 'ECUATORIANO SUIZA',
    tipocliente: 'Natural',
    ramo: 'Robo',
    coberturaGeneral: "Prueba",
    coberturaAdicional: "Prueba",
    observaciones: "Prueba",
    deducibles: 10,
    formaPago: "Debito a la Cuenta",
  },
  {
    key: '7',
    name: 'Sofía Martínez',
    aseguradora: 'LA UNIÓN',
    tipocliente: 'Natural',
    ramo: 'Robo',
    coberturaGeneral: "Prueba",
    coberturaAdicional: "Prueba",
    observaciones: "Prueba",
    deducibles: 10,
    formaPago: "Tarjeta de Crédito",
  },
  {
    key: '8',
    name: 'Sofía Martínez',
    aseguradora: 'COLON',
    tipocliente: 'Natural',
    ramo: 'Vehiculos',
    coberturaGeneral: "Prueba",
    coberturaAdicional: "Prueba",
    observaciones: "Prueba",
    deducibles: 10,
    formaPago: "Financiamento Directo",
  },
  {
    key: '9',
    name: 'Sofía Martínez',
    aseguradora: 'GENERALI',
    tipocliente: 'Natural',
    ramo: 'Vida Colectiva',
    coberturaGeneral: "Prueba",
    coberturaAdicional: "Prueba",
    observaciones: "Prueba",
    deducibles: 10,
    formaPago: "Debito a la Cuenta",
  },
  {
    key: '11',
    name: 'Sofía Martínez',
    aseguradora: 'LA UNIÓN',
    tipocliente: 'Natural',
    ramo: 'Cumplimiento de Contrato',
    coberturaGeneral: "Prueba",
    coberturaAdicional: "Prueba",
    observaciones: "Prueba",
    deducibles: 10,
    formaPago: "Debito a la Cuenta",
  },
  {
    key: '12',
    name: 'Sofía Martínez',
    aseguradora: 'SEGUROS CONFIANZA S.A.',
    tipocliente: 'Natural',
    ramo: 'Cumplimiento de Contrato',
    coberturaGeneral: "Prueba",
    coberturaAdicional: "Prueba",
    observaciones: "Prueba",
    deducibles: 10,
    formaPago: "Financiamento Directo",
  },
];

type MenuItem = GetProp<MenuProps, 'items'>[number];
export const item: MenuItem[] = [
  {
    key: 'sub2',
    label: 'Cotización',
    icon: <FileDoneOutlined />,
    children: [
      { key: '/usercotizacion', label: 'Generar Cotización' },
      { key: '/catalog-user-cotizacion', label: 'Registro Cotizaciones' },
      { key: '/cotizacion', label: 'Cotizaciones' },

    ],
  },
  {
    key: '1',
    icon: <MailOutlined />,
    label: 'Póliza',
    children: [
      { key: '/poliza', label: 'Generar Poliza' },

    ],
  },
  {
    key: '2',
    icon: <CalendarOutlined />,
    label: 'Siniestro',
  },
];

export const itemAdmin: MenuItem[] = [
  {
    key: 'sub2',
    label: 'Cotización',
    icon: <FileDoneOutlined />,
    children: [
      { key: '/dashboard', label: 'Registro Cotizaciones' },

    ],
  },
  {
    key: '1',
    icon: <MailOutlined />,
    label: 'Póliza',
  },
  {
    key: '2',
    icon: <CalendarOutlined />,
    label: 'Siniestro',
  },
];